## Imports & Display Options

In [21]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_columns', 45)

## Load Data

In [3]:
df_20161101 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161101.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 1 Loaded")
df_20161108 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161108.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 2 Loaded")
df_20161116 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161116.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 3 Loaded")
df_20161122 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161122.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 4 Loaded")
df_20161129 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161129.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 5 Loaded")
df_20161206 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20161206.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 6 Loaded")
df_20170110 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170110.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 7 Loaded")
df_20170116 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170116.csv', sep='|', na_values=['nan', ' ', '  '], low_memory=False)
print("Dataset 8 Loaded")
df_20170117 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170117.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 9 Loaded")
df_20170124 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170124.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 10 Loaded")
df_20170131 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170131.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 11 Loaded")
df_20170207 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170207.csv', sep='|', na_values=['nan', ' ', '  '], low_memory=False)
print("Dataset 12 Loaded")
df_20170214 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170214.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 13 Loaded")
df_20170221 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170221.csv', sep='|', na_values=['nan', ' ', '  '])
print("Dataset 14 Loaded")
df_20170301 =  pd.read_csv('/Users/ryanallred/Desktop/Rx_Claims/Rx_BenefitPlan_20170301.csv', sep='|', na_values=['nan', ' ', '  '], low_memory=False)
print("Dataset 15 Loaded")

Dataset 1 Loaded
Dataset 2 Loaded
Dataset 3 Loaded
Dataset 4 Loaded
Dataset 5 Loaded
Dataset 6 Loaded

/Users/ryanallred/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Dataset 7 Loaded
Dataset 8 Loaded
Dataset 9 Loaded
Dataset 10 Loaded
Dataset 11 Loaded
Dataset 12 Loaded
Dataset 13 Loaded
Dataset 14 Loaded
Dataset 15 Loaded

In [4]:
df = pd.concat([df_20161101, df_20161108, df_20161116, df_20161122, df_20161129,
                                     df_20161206, df_20170110, df_20170116, df_20170117, df_20170124, 
                                     df_20170131, df_20170207, df_20170214, df_20170221, df_20170301])

## View Dataframe Shape and Head

In [5]:
print(df.shape)
df.head()

(4431552, 42)

,AHFSTherapeuticClassCode,ClaimID,ClaimStatus,CoInsurance,CompoundDrugIndicator,Copay,DAWCode,DateFilled,DaysSupply,Deductible,DispensingFee,DrugLabelName,FillNumber,FormularyStatus,Generic,GroupNumber,IngredientCost,MailOrderPharmacy,MemberID,MultisourceIndicator,NDCCode,OutOfPocket,PBMVendor,PaidAmount,PaidOrAdjudicatedDate,PharmacyCity,PharmacyNPI,PharmacyName,PharmacyNumber,PharmacyState,PharmacyStreetAddress1,PharmacyStreetAddress2,PharmacyTaxId,PharmacyZip,PrescriberFirstName,PrescriberID,PresriberLastName,Quantity,RxNumber,SeqNum,UnitMeasure,punbr_grnbr
0,40282000,00005392286554,P,nan,1,30,0,2016-10-24,90,0,0,HYDROCHLOROTHIAZIDE ...,N,Y,Y,A57,30,N,HHA570036,1,16729018317,30,MedImpact,0,2016-10-24,DERRY ...,3004861,RITE AID PHARMACY 03310 ...,NaN,NH,59 ROCKINGHAM ST ...,NaN,231614034,03038-2119,NaN,1053528364,NaN,90,1260961,0,Drops,001A57
1,28129200,00005394709754,P,nan,1,10,0,2016-10-25,30,0,2,GABAPENTIN ...,R,Y,Y,A57,16,N,HHA570036,1,52343003290,10,MedImpact,7,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1396706677,NaN,90,5058804,1,Capsule,001A57
2,84920000,00005394709631,P,nan,1,20,0,2016-10-25,30,0,2,SANTYL ...,R,Y,N,A57,55,N,HHA570036,3,50484001030,20,MedImpact,36,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5231123,1,Ointment,001A57
3,40280800,00005396245992,P,nan,1,10,0,2016-10-26,30,0,2,TORSEMIDE ...,N,Y,Y,A57,35,N,HHA570036,1,54007725,10,MedImpact,27,2016-10-26,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5307931,1,Tablet,001A57
4,28080800,00005396901904,J,nan,1,0,0,2016-10-27,30,0,0,OXYCODONE HCL ...,N,O,Y,A57,0,N,HHA570036,1,60429051601,0,MedImpact,0,2016-10-27,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,270,5308269,1,Tablet,001A57

## Count Missing Values

In [6]:
# Count Missing Values
df.isnull().sum().sort_values(ascending = False)

PharmacyStreetAddress2      3093678
PrescriberFirstName          946460
PharmacyTaxId                412298
AHFSTherapeuticClassCode     336672
PharmacyState                309527
PharmacyCity                 309515
PharmacyStreetAddress1       309515
PharmacyZip                  309509
FormularyStatus              290636
PresriberLastName            244009
PharmacyName                 218248
DispensingFee                168770
IngredientCost               168394
ClaimStatus                  163611
RxNumber                     160890
PharmacyNPI                  126246
CoInsurance                  115430
PharmacyNumber                80214
UnitMeasure                   57101
DrugLabelName                 53061
Quantity                      53054
Generic                       16365
CompoundDrugIndicator          8723
PrescriberID                   4016
DAWCode                        3640
MailOrderPharmacy               586
Deductible                       36
NDCCode                           3
MultisourceIndicator              3
GroupNumber                       0
FillNumber                        0
MemberID                          0
OutOfPocket                       0
DaysSupply                        0
DateFilled                        0
PBMVendor                         0
Copay                             0
PaidAmount                        0
PaidOrAdjudicatedDate             0
SeqNum                            0
ClaimID                           0
punbr_grnbr                       0
dtype: int64

# Number of Claims by PBM

In [7]:
df['PBMVendor'].value_counts()

CVSPAL4000         2764364
Medco               630260
MedImpact           574053
MaxorPlus           160890
Magellan            102802
Envision             95176
RXPreferred          53054
SouthernScripts      18836
Welldyne             14211
Navitus               7504
Nemop                 5033
OptumRX               3640
National              1353
CanaRX                 376
Name: PBMVendor, dtype: int64

## Number of Claims by NDC Code

In [8]:
df['NDCCode'].value_counts()

59310057922    52028
55111015810    27974
54327099       26288
68180051403    24712
29300012810    18758
68180051503    17990
60505082901    16426
781261305      16070
59762306001    15147
53746046605    14591
68180051703    13999
555901658      12932
65862005299    12920
68180051303    12749
52027303       12055
13668001005    11830
50111043301    11673
10370010150    11519
88221905       11181
173068220      10960
378232105      10762
172208380      10607
173069600      10268
378395277       9970
378395177       9960
378395077       9907
93742698        9742
69422030        9633
555904358       9489
53746010901     9384
               ...
58160082052        1
68084062221        1
904573651          1
63323069404        1
13668008830        1
51672135008        1
68382076405        1
62559038001        1
51079051820        1
66758016013        1
60505357901        1
55111017005        1
51079009020        1
59212042316        1
456068801          1
51991081905        1
50458009105        1
52343003101        1
50383072015        1
70408014134        1
67402004045        1
955104530          1
65862009601        1
60505016805        1
555006605          1
67877021901        1
555048805          1
40076010150        1
51927143500        1
64896069151        1
Name: NDCCode, Length: 21583, dtype: int64

## Replace multiple whitespace with single whitespace in DrugLabelName

In [9]:
df['DrugLabelName'] = df['DrugLabelName'].astype(str)
df['DrugLabelName'] = df['DrugLabelName'].apply(lambda drug: ' '.join(drug.split()))

## Filter out rows where ingredient cost is <= 0

In [18]:
df = df[df['IngredientCost'] > 0]
print(df.shape)
df.head()

(3703065, 42)

,AHFSTherapeuticClassCode,ClaimID,ClaimStatus,CoInsurance,CompoundDrugIndicator,Copay,DAWCode,DateFilled,DaysSupply,Deductible,DispensingFee,DrugLabelName,FillNumber,FormularyStatus,Generic,GroupNumber,IngredientCost,MailOrderPharmacy,MemberID,MultisourceIndicator,NDCCode,OutOfPocket,PBMVendor,PaidAmount,PaidOrAdjudicatedDate,PharmacyCity,PharmacyNPI,PharmacyName,PharmacyNumber,PharmacyState,PharmacyStreetAddress1,PharmacyStreetAddress2,PharmacyTaxId,PharmacyZip,PrescriberFirstName,PrescriberID,PresriberLastName,Quantity,RxNumber,SeqNum,UnitMeasure,punbr_grnbr
0,40282000,00005392286554,P,nan,1,30,0,2016-10-24,90,0,0,HYDROCHLOROTHIAZIDE,N,Y,Y,A57,30,N,HHA570036,1,16729018317,30,MedImpact,0,2016-10-24,DERRY ...,3004861,RITE AID PHARMACY 03310 ...,NaN,NH,59 ROCKINGHAM ST ...,NaN,231614034,03038-2119,NaN,1053528364,NaN,90,1260961,0,Drops,001A57
1,28129200,00005394709754,P,nan,1,10,0,2016-10-25,30,0,2,GABAPENTIN,R,Y,Y,A57,16,N,HHA570036,1,52343003290,10,MedImpact,7,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1396706677,NaN,90,5058804,1,Capsule,001A57
2,84920000,00005394709631,P,nan,1,20,0,2016-10-25,30,0,2,SANTYL,R,Y,N,A57,55,N,HHA570036,3,50484001030,20,MedImpact,36,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5231123,1,Ointment,001A57
3,40280800,00005396245992,P,nan,1,10,0,2016-10-26,30,0,2,TORSEMIDE,N,Y,Y,A57,35,N,HHA570036,1,54007725,10,MedImpact,27,2016-10-26,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5307931,1,Tablet,001A57
5,24240000,00005397740988,J,nan,1,0,0,2016-10-27,30,0,0,TOPROL XL,N,Y,Y,A57,36,N,HHA570036,1,186109235,0,MedImpact,0,2016-10-27,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5308267,1,Tablet,001A57

## Filter out rows where quantity <= 0

In [19]:
df = df[df['Quantity'] > 0]
print(df.shape)
df.head()

(3639401, 42)

,AHFSTherapeuticClassCode,ClaimID,ClaimStatus,CoInsurance,CompoundDrugIndicator,Copay,DAWCode,DateFilled,DaysSupply,Deductible,DispensingFee,DrugLabelName,FillNumber,FormularyStatus,Generic,GroupNumber,IngredientCost,MailOrderPharmacy,MemberID,MultisourceIndicator,NDCCode,OutOfPocket,PBMVendor,PaidAmount,PaidOrAdjudicatedDate,PharmacyCity,PharmacyNPI,PharmacyName,PharmacyNumber,PharmacyState,PharmacyStreetAddress1,PharmacyStreetAddress2,PharmacyTaxId,PharmacyZip,PrescriberFirstName,PrescriberID,PresriberLastName,Quantity,RxNumber,SeqNum,UnitMeasure,punbr_grnbr
0,40282000,00005392286554,P,nan,1,30,0,2016-10-24,90,0,0,HYDROCHLOROTHIAZIDE,N,Y,Y,A57,30,N,HHA570036,1,16729018317,30,MedImpact,0,2016-10-24,DERRY ...,3004861,RITE AID PHARMACY 03310 ...,NaN,NH,59 ROCKINGHAM ST ...,NaN,231614034,03038-2119,NaN,1053528364,NaN,90,1260961,0,Drops,001A57
1,28129200,00005394709754,P,nan,1,10,0,2016-10-25,30,0,2,GABAPENTIN,R,Y,Y,A57,16,N,HHA570036,1,52343003290,10,MedImpact,7,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1396706677,NaN,90,5058804,1,Capsule,001A57
2,84920000,00005394709631,P,nan,1,20,0,2016-10-25,30,0,2,SANTYL,R,Y,N,A57,55,N,HHA570036,3,50484001030,20,MedImpact,36,2016-10-25,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5231123,1,Ointment,001A57
3,40280800,00005396245992,P,nan,1,10,0,2016-10-26,30,0,2,TORSEMIDE,N,Y,Y,A57,35,N,HHA570036,1,54007725,10,MedImpact,27,2016-10-26,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5307931,1,Tablet,001A57
5,24240000,00005397740988,J,nan,1,0,0,2016-10-27,30,0,0,TOPROL XL,N,Y,Y,A57,36,N,HHA570036,1,186109235,0,MedImpact,0,2016-10-27,MANCHESTER ...,3005255,MANCHESTER VAMC PHARMACY ...,NaN,NH,718 SMYTH RD ...,NaN,20222932,03104-0000,NaN,1770769515,NaN,60,5308267,1,Tablet,001A57

## Groupby NDC Code
## Create Dataframe of the Groupby to get Counts of NDC Codes

In [30]:
grouped = df.groupby(by='NDCCode', as_index=False).size()
grouped.name = 'count'
grouped = grouped.reset_index()
grouped.head()

     NDCCode  count
0       0.00    633
1   30001.00      1
2 2143301.00      3
3 2143380.00    543
4 2143401.00      9

## Find Average of IngredientCost by NCDCode and add to dataframe

In [39]:
average_ingredient_cost_list = df.groupby('NDCCode')['IngredientCost'].mean().tolist()
average_ingredient_cost_series = pd.Series(average_ingredient_cost_list)
grouped['AverageIngredientCost'] = average_ingredient_cost_series.values
grouped.head()

     NDCCode  count  AverageIngredientCost
0       0.00    633                 867.22
1   30001.00      1                   0.84
2 2143301.00      3                1516.98
3 2143380.00    543                 744.47
4 2143401.00      9                 565.72

## Find Average of Quantity by NCDCode and add to dataframe

In [40]:
average_quantity_list = df.groupby('NDCCode')['Quantity'].mean().tolist()
average_quantity_series = pd.Series(average_quantity_list)
grouped['AverageQuantity'] = average_quantity_series.values
grouped.head()

     NDCCode  count  AverageIngredientCost  AverageQuantity
0       0.00    633                 867.22           174.11
1   30001.00      1                   0.84             1.00
2 2143301.00      3                1516.98             4.67
3 2143380.00    543                 744.47             2.54
4 2143401.00      9                 565.72             2.00

## Sort by NDC Code Counts

In [41]:
sorted = grouped.sort_values(by=['count'], ascending=False)
sorted.head()

             NDCCode  count  AverageIngredientCost  AverageQuantity
15220 59310057922.00  42836                  62.03             9.72
14459 55111015810.00  22967                  56.34            45.71
761      54327099.00  21522                  45.26            19.14
19460 68180051403.00  21244                   8.87            42.96
19463 68180051503.00  15624                  10.35            44.60

## Groupby DrugLabelName and sort to check if NDC Code and DrugLabelName are 1:1

In [42]:
names = df.groupby(by='DrugLabelName', as_index=False).size()
names.name = 'count'
names = names.reset_index()
names.head()

               DrugLabelName  count
0                                 6
1    10ML LL SYRN MIS 20GX1"      1
2  1ML MEDSAVER SYRINGE/REGU      2
3   1ML SYRINGE MIS 28GX1/2"     12
4    1ML TB SYRNG MIS 21GX1"      1

In [43]:
sorted_names = names.sort_values(by=['count'], ascending=False)
sorted_names.head()

              DrugLabelName  count
6159             LISINOPRIL  45094
8966         PROAIR HFA AER  31305
4327  FLUTICASONE SPR 50MCG  27922
9848            SIMVASTATIN  27900
7929             OMEPRAZOLE  27834

# DrugLabelNames are not unique to NDCCodes!!!
## Get the most common DrugLabelName for a given NDC Code and use that as the DrugLabelName

In [ ]:
drug_labels = []
for row in sorted.iterrows():
    temp_df = df[df.NDCCode == row[1][0]]
    drug_labels.append(temp_df.DrugLabelName.value_counts().index.tolist()[0])

print(drug_labels)

In [ ]:
drug_label_list = pd.Series(drug_labels)
sorted['DrugLabel'] = drug_label_list.values

In [ ]:
sorted.head()

## Export to CSV Sorted list of NDC Code counts with Drug Label Names

In [143]:
sorted.to_csv('claims_by_NDCCode.csv', index=False)